language: ruby
rvm:
- 2.1.5
addons:
  code_climate:
    repo_token: 34e63aa37c4c64f6d6f2a64501918ff70d96b366d8bca9ec6a257ff0684d0ce4
notifications:
  slack:
    secure: BewidAAO3w1MrgUWIjwZHlVemkFdUKieLPQB9Bj/V8wiP5Xg95Btsf48kuMn9g4JT7s9L8l03bZe06T/XdXWz4VZ8HKae98Q+79+yBaxNk3fyFtHzGPHMPGuDe8SfKdiJHEKrhNBH3Y4RuBLcM9iPJ+k0SlkxmC/eaCzHnrvMeo=
env:
  API_HOST: http://localhost:9393
  global:
  - secure: laSfzHnQl7fNqU5Dusbo4e83lVyN5Ir4oAhudy38EmZj/SzVg27LRLRDTZrQLsh1vhanT/ovq9WMrv3jiZX2oZi5AVWfDwaeF/pnbUrf0Rm5GgWYzPyfP1M7jXLHhIpa3LiRNfiQWksNrknL3gdDz/rT/z5LxKTGrFs8y9Ic5WU=
  - secure: iPScpPZXd2bKQts5xFqKRDsxjwpIZB6F7wtljFKPaevQZdgdrn3UJm1uzSRf9FGMSeuRGzrE4QdX3XQdT1ivbwS0wuqXMrcPSfRJoUXa9N3rUEh+k2L/kqQ5PISphs60lQOxOMsxkpX1vtQeALP+hv12tTNu4s6xmSYYIL9U63k=
  - secure: PKuUVoycIC4Eoah1n8A9UMu80KkzPjdTbroPsJgax/YH/mVPoGyubconqgqPIFoDsy5nHlPGwr4zAAhAYOBD7idFu6r98PtnqV126Xa1Bu8SGl6aPKIxuCaTwfzpWtBwCxdGmkmsaVof5RIw+T3C7xa24P/7xLYBPPBV7pL5HpM=
  - secure: Jif2E3gIFxlpMjdjc9GDtQ+ThSpUlEcjfEW0HqvW9RwOJDitP945ju1c54U+boQXMy68f1RPklfQ9toLg7bAzABXdLMfDAsP/uhxnvROJQoAUAj9HSjmh3b2P1dc/7oO0y22aycGSajB4uO+nZp2d9bK9KF5IUPuxAP9QP514Qk=
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/application.yml.example config/application.yml
