common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *common
  database: brechin-collected-development

test:
  <<: *common
  database: brechin-collected-test

production:
  <<: *common
  database: brechin-collected-production
